### ISSUE TITLE
Support for SwiftBond

### ISSUE THREAD

**Issue by harmeetsingh** [icanzilb/Timelane#3]
Would be nice to have direct support for SwiftBond https://github.com/DeclarativeHub/Bond

**Comment by icanzilb** [comment]
If that seems like a good idea, do open an issue on the Bond repo, the creator is already looking into integration with Timelane (https://github.com/icanzilb/TimelaneCore/pull/3) 👍🏼

**Comment by harmeetsingh** [comment]
@icanzilb that change is merged in now so is it possible to use Timeline with SwiftBond? :D

**Comment by icanzilb** [comment]
If that seems like a good idea, do open an issue on the Bond repo, the creator is already looking into integration with Timelane

**Comment by icanzilb** [comment]
Inactive for 2 months
