### ISSUE TITLE
Add homebrew support

### ISSUE THREAD

**Issue by icanzilb** [icanzilb/Timelane#6]
No idea how - need to investigate

**Comment by toastersocks** [comment]
I could look into this. Are you wanting to add homebrew support for installing the app that installs the Timelane instrument? Or do you want homebrew to install the instrument directly?

**Comment by icanzilb** [comment]
I think ideally we'd install the app - this is the starting point for developers, including short docs and links to the supported libraries. The instrument by itself is not a good starting experience.

**Comment by icanzilb** [comment]
And thanks for noticing this issue and willing to contribute!

**Comment by justinswart** [comment]
I was curious about how to do that so I went ahead and opened a PR: https://github.com/Homebrew/homebrew-cask/pull/80080.

Thanks for the tool!

**Comment by justinswart** [comment]
Looks like it merged so you can now install using Homebrew with `brew cask install timelane` 👍

**Comment by icanzilb** [comment]
@justinswart oh, cool! does the Homebrew support require some kind of maintenance?

**Comment by justinswart** [comment]
> does the Homebrew support require some kind of maintenance?

Yeah the [cask](https://github.com/justinswart/homebrew-cask/blob/cc33b2395c7bfde97b497a80364ec275070c771f/Casks/timelane.rb) looks like this:

```ruby
cask 'timelane' do
  version '1.0.0'
  sha256 'cee79be7ffd8f1e6d06cc937fe1addc895fa531a99c439cbe7fbd30589c6fed8'

  # github.com/icanzilb/Timelane was verified as official when first introduced to the cask
  url "https://github.com/icanzilb/Timelane/releases/download/#{version}/Timelane.app-#{version}.zip"
  appcast 'https://github.com/icanzilb/Timelane/releases.atom'
  name 'Timelane'
  homepage 'http://timelane.tools/'

  app 'Timelane.app'
end
```
I think when you release a new version, we'd have to update `version` and `sha256`.

You can generate a new `sha256` by running `shasum -a 256 <zip file>`.

As long as the format of the version number in the zip file remains the same then you shouldn't need to change the `url` value.

**Comment by icanzilb** [comment]
Cool! Just to make sure, does that mean update the cask at every release of Timelane?

**Comment by justinswart** [comment]
@icanzilb yes, I believe so - for each stable release we would want to increment the version and update the checksum.

**Comment by icanzilb** [comment]
Cool, thank you very much for looking into this!
